---

# Unix users to create everywhere.

users:
  - mxs
  - faltad

# VPN settings

netname: midearth
vpn_interface: tun0
vpn_netmask: 255.255.255.0
vpn_subnet_cidr_netmask: 32
physical_ip: "{{ ansible_enp1s0.ipv4.address }}"
