---

- name: Setup kubernetes master node
  hosts: master
  roles:
    - master

- hosts: master
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: worker
  tasks:
    - name: join cluster
      shell: "{{ hostvars['gamgee']['join_command'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

- hosts: master
  roles:
    - nginx


