---

- name: set up base system configuration
  import_playbook: base.yml

- name: set up intra-cluster cluster networking
  import_playbook: cluster.yml

- name: set up kubernetes cluster
  import_playbook: cluster.yml
