---

# Main playbook to setup the entire cluster.

- name: Setup all machines in the cluster
  hosts: all
  roles:
    - base

- name: Setup kubernetes master node
  hosts: master
  roles:
    - master
