---

# Tasks to setup an intra-cluster network.

- name: set up tinc packages
  apt:
    name:
      - tinc
    state: present

- name: enable tinc
  systemd:
    name: tinc
    enabled: yes
    state: started

- name: create tinc network name directory
  file:
    path: /etc/tinc/{{ netname }}/hosts
    recurse: True
    state: directory

- name: add network to autostart list
  template:
    src: nets.boot
    dest: /etc/tinc/nets.boot
  notify:
    - restart tinc
