---

# Tasks to setup a master k8s cluster.

- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ physical_ip }}
  args:
    creates: /etc/kubernetes/admin.conf

- name: create kube user directories
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
  with_flattened:
    - "{{ users }}"
    - ['root']

- name: add kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
  with_flattened:
    - "{{ users }}"
    - ['root']
