---

# Tasks to setup Unix users.

- name: create the 'mxs' user
  user: name=mxs append=yes state=present createhome=yes shell=/bin/bash

- name: allow 'mxs' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'mxs ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the 'mxs' user
  authorized_key: user=mxs key="{{item}}"
  with_file:
    - files/user-mxs.pub
