---

# Tasks to setup Unix users.

- name: create unix user
  user: name="{{ item }}" append=yes state=present createhome=yes shell=/bin/bash groups=sudo
  loop: "{{ users }}"

- name: configure sudo
  lineinfile:
    dest: /etc/sudoers
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  loop: "{{ users }}"

- name: set up authorized keys for the '{{ user }}' user
  authorized_key: user=mxs key="{{ lookup('file', 'files/user-' + item + '.pub') }}"
  loop: "{{ users }}"
